---
- name: Update web servers
  hosts: localhost
  remote_user: root
  tasks:
    - name: Ensure php-pecl-memcache is at the latest version
      ansible.builtin.yum:
        name: php-pecl-memcache
        state: latest

    - name: Ensure amazon-efs-utils is at the latest version
      ansible.builtin.yum:
        name: amazon-efs-utils
        state: latest

    - name: Ensure curl is at the latest version
      ansible.builtin.yum:
        name: curl
        state: latest

    - name: Ensure nginx is at the latest version
      ansible.builtin.yum:
        name: nginx
        state: latest

    - name: Ensure php is at the latest version
      ansible.builtin.yum:
        name: php
        state: latest

    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/html"
        remote_src: yes
        creates: "/var/www/html/wordpress"
